#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

# Add NGINX Configuration
echo "
map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
}

# RStudio Server
server {
    listen 8789;
    listen [::]:8789;
    server_name $RSTUDIO_DOMAIN;
    client_max_body_size 2G;
    location / {
        proxy_pass http://localhost:8787;
        proxy_redirect http://localhost:8787/ https://$RSTUDIO_DOMAIN/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 20d;
        proxy_set_header Host $RSTUDIO_DOMAIN:443;
        proxy_set_header X-Forwarded-Host $RSTUDIO_DOMAIN:443;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Accept-Encoding \"\";
        sub_filter '</head>' '<style>
        #rstudio_container > div:nth-child(2) > div > div:nth-child(4) > div > div:nth-child(4) > div > div > div:nth-child(4) > div {
          display: none !important;
        }
        #rstudio_container > div:nth-child(2) > div > div:nth-child(4) > div > div:nth-child(4) > div > div > div:nth-child(4),
        #rstudio_container > div:nth-child(2) > div > div:nth-child(4) > div > div:nth-child(4) > div > div > div:nth-child(5) {
          z-index: -10 !important;
        }
        #rstudio_container > div:nth-child(2) > div > div:nth-child(4) > div > div:nth-child(4) > div > div > div:nth-child(6) {
          bottom: 27px;
        }
        </style></head>';
        sub_filter_once on;
    }
}

# VSCode Server
server {
    listen 8789;
    listen [::]:8789;
    server_name $VSCODE_DOMAIN;
    client_max_body_size 2G;
    location / {
        proxy_pass http://localhost:8788;
        proxy_redirect http://localhost:8788/ https://$VSCODE_DOMAIN/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 20d;
        proxy_set_header Host $VSCODE_DOMAIN:443;
        proxy_set_header X-Forwarded-Host $VSCODE_DOMAIN:443;
        proxy_set_header X-Forwarded-Proto https;
        # Enable this if using openvscode-server service
        # proxy_set_header Cookie \"vscode-tkn=0000\";
        # This is to insert a font declaration for the desired font
        proxy_set_header Accept-Encoding \"\";
        sub_filter '</head>' '<style>@font-face { font-family: JuliaMono; src: url(\"fonts/JuliaMono.woff2\") }</style></head>';
        sub_filter_once on;
    }
    # Fonts serving
    location /fonts/ {
        alias /etc/rstudio/fonts/;
    }

}

# Port 8888
server {
    listen 8789;
    listen [::]:8789;
    server_name 8888.$PROXY_DOMAIN;
    client_max_body_size 2G;
    location / {
        proxy_pass http://localhost:8888;
        proxy_redirect http://localhost:8888/ https://8888.$PROXY_DOMAIN/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 20d;
        proxy_set_header Host 8888.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Host 8888.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Port 5500
server {
    listen 8789;
    listen [::]:8789;
    server_name 5500.$PROXY_DOMAIN;
    client_max_body_size 2G;
    location / {
        proxy_pass http://localhost:5500;
        proxy_redirect http://localhost:5500/ https://5500.$PROXY_DOMAIN/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 20d;
        proxy_set_header Host 5500.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Host 5500.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# Port 3838
server {
    listen 8789;
    listen [::]:8789;
    server_name 3838.$PROXY_DOMAIN;
    client_max_body_size 2G;
    location / {
        proxy_pass http://localhost:3838;
        # proxy_redirect http://localhost:3838/ https://3838.$PROXY_DOMAIN/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_read_timeout 20d;
        proxy_set_header Host 3838.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Host 3838.$PROXY_DOMAIN:443;
        proxy_set_header X-Forwarded-Proto https;
    }
}
" > /etc/nginx/sites-enabled/default
echo "
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    access_log /dev/null;
    error_log /dev/null;

    gzip on;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

}
" > /etc/nginx/nginx.conf

# Start NGINX Server
nginx -g "daemon off;"
