image:
  file: .gitpod.Dockerfile

tasks:
  - name: GitHub Container Registry Login 
    command: echo $GITHUB_PAT | docker login ghcr.io --username $GITHUB_USERNAME --password-stdin && exit

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.makefile-tools
