image: ghcr.io/tjpalanca/tjcloud/gitpod:latest

tasks:
  - name: GitHub Container Regisry Login 
    command: echo $GITHUB_PAT | docker login ghcr.io --username $GITHUB_USERNAME --password-stdin

vscode:
  extensions:
    - ms-azuretools.vscode-docker
