image: ghcr.io/tjpalanca/tjcloud/gitpod:latest

tasks:
  - name: Production Setup 
    init: /setup/production.sh
  - name: GitHub Container Registry Login 
    command: echo $GITHUB_PAT | docker login ghcr.io --username $GITHUB_USERNAME --password-stdin && exit

vscode:
  extensions:
    - ms-azuretools.vscode-docker
