#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

if [[ "$RESOLUTION" == "" ]]; then
    RESOLUTION=960x540x24
fi

Xvfb "$DISPLAY" -screen 0 "$RESOLUTION"
