kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: werner
  name: shinyproxy
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy
  namespace: werner
subjects:
  - kind: ServiceAccount
    name: default
    namespace: werner
roleRef:
  kind: Role
  name: shinyproxy
  apiGroup: rbac.authorization.k8s.io
