# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tjcloud',
                'doc_host': 'https://tjpalanca.com',
                'git_url': 'https://github.com/tjpalanca/tjcloud.git',
                'lib_path': 'tjcloud'},
  'syms': { 'tjcloud.linode': { 'tjcloud.linode.LinodeClient': ('linode.html#linodeclient', 'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.__init__': ('linode.html#linodeclient.__init__', 'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.api_call': ('linode.html#linodeclient.api_call', 'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.disable_firewall': ( 'linode.html#linodeclient.disable_firewall',
                                                                                  'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.enable_firewall': ( 'linode.html#linodeclient.enable_firewall',
                                                                                 'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.firewall_id': ('linode.html#linodeclient.firewall_id', 'tjcloud/linode.py'),
                                'tjcloud.linode.LinodeClient.is_firewall_enabled': ( 'linode.html#linodeclient.is_firewall_enabled',
                                                                                     'tjcloud/linode.py'),
                                'tjcloud.linode.disable_firewall': ('linode.html#disable_firewall', 'tjcloud/linode.py'),
                                'tjcloud.linode.enable_firewall': ('linode.html#enable_firewall', 'tjcloud/linode.py')}}}
