# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/linode.ipynb.

# %% auto 0
__all__ = ['LinodeClient']

# %% ../notebooks/linode.ipynb 1
import os
import requests

from functools import cached_property

# %% ../notebooks/linode.ipynb 2
class LinodeClient:
    """
    A client instance that facilitates communication with the Linode API.
    """

    def __init__(self, token):
        self.base_url = "https://api.linode.com/v4"
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {token}",
            }
        )

    def api_call(self, method, endpoint, data=None):
        url = f"{self.base_url}{endpoint}"
        response = self.session.request(method, url, json=data)
        return response

    @cached_property
    def firewall_id(self, label="tjcloud"):
        firewalls = self.api_call("GET", "/networking/firewalls").json()["data"]
        firewall = list(filter(lambda f: f["label"] == label, firewalls))[0]
        return firewall["id"]

    def enable_firewall(self, status="enabled"):
        self.api_call(
            "PUT", f"/networking/firewalls/{self.firewall_id}", data={"status": status}
        )

    def disable_firewall(self):
        self.enable_firewall(status="disabled")

    @property
    def is_firewall_enabled(self):
        firewall = self.api_call(
            "GET", f"/networking/firewalls/{self.firewall_id}"
        ).json()
        return firewall["status"] == "enabled"
