#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

while true
do
    pkill --full --parent=1 helpServer\.R$
    pkill --full --parent=1 helpServer\.R$
    sleep 10
done