server:
  useForwardHeaders: true

spring:
  mail:
    host: smtp.gmail.com
    # TLS: 587 SSL: 465 Plain: 25
    port: 465
    username: ${SHINYPROXY_EMAIL_APP_USERNAME}
    password: ${SHINYPROXY_EMAIL_APP_PASSWORD}
    properties:
      # For StartTLS
      # mail.smtp.starttls.enable: true
      # For SSL
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

proxy:
  title: "TJApps"
  logo-url: file:///opt/shinyproxy/template/template/assets/logo.png
  favicon-path: template/template/assets/logo.png
  template-path: ./template/template
  heartbeat-timeout: 60000
  port: 8080
  support:
    mail-to-address: support@tjpalanca.com
  authentication: keycloak
  admin-groups: shinyproxy-admin
  keycloak:
    realm: master
    auth-server-url: https://keycloak.tjpalanca.com:443/auth
    resource: ${KEYCLOAK_CLIENT_ID}
    credentials-secret: ${KEYCLOAK_CLIENT_SECRET}
    confidential-port: 443
    name-attribute: email
  container-backend: kubernetes
  container-wait-time: 60000
  kubernetes:
    internal-networking: true
    url: https://kubernetes.default.svc
    namespace: ${CLOUD66_STACK_NAMESPACE}
    image-pull-secret: regcred
    image-pull-policy: ${SHINYPROXY_IMAGE_PULL_POLICY:IfNotPresent}
  specs:
    - id: tjtools
      display-name: TJTools
      logo-url: file:///opt/shinyproxy/template/template/assets/logo.png
      container-image: tjpalanca/apps:tjtools-latest
      description: Random tools for various purposes
      container-env:
        TJTOOLS_PASSWORD: ${TJTOOLS_PASSWORD}
