#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

# Set up environment
chsh --shell /bin/zsh $DEFAULT_USER
export HOME=/home/$DEFAULT_USER
usermod -aG docker $DEFAULT_USER
chown 1000:1000 /var/run/docker.sock
echo "$DEFAULT_USER ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers.d/nopasswd > /dev/null

# Run code-server
exec s6-setuidgid 1000:1000 \
    /usr/bin/code-server \
    --auth none \
    --disable-telemetry \
    --bind-addr 0.0.0.0:3333
