# RStudio Gateway
FROM quay.io/pusher/oauth2_proxy:v3.2.0
MAINTAINER TJ Palanca <mail@tjpalanca.com>

# Copy Authenticated Email List
USER root
RUN mkdir -p /src
COPY authenticated_emails.cfg /src/authenticated_emails.cfg
USER 2000:2000

