apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: wistfulness
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""] 
  resourceNames: ["tailscale-auth"]
  resources: ["secrets"]
  verbs: ["get", "update"]
