version: 2
services:
  ingress-nginx-controller:
    traffic_matches:
    - <INSERT HOSTNAMES HERE>
    service_account_name: ingress-nginx
    tags:
    - shiny
    - app.kubernetes.io/name=ingress-nginx
    - app.kubernetes.io/instance=ingress-nginx
    - app.kubernetes.io/version=0.47.0
    - app.kubernetes.io/component=controller
    image: k8s.gcr.io/ingress-nginx/controller:v0.46.0@sha256:52f0058bed0a17ab0fb35628ba97e8d52b5d32299fbc03cc0f6c7b9ff036b61a
    command: |-
      /nginx-ingress-controller
      --election-id=ingress-controller-leader
      --ingress-class=nginx
      --configmap=$(POD_NAMESPACE)/cloud66.app.config.store.where.name.equals.ingress-nginx-controller
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
    security_context:
      privileged: true
      run_as_user: 101
    env_vars:
      POD_NAME: "$(CLOUD66_POD_NAME)"
      POD_NAMESPACE: "$(CLOUD66_STACK_NAMESPACE)"
      LD_PRELOAD: "/usr/local/lib/libmimalloc.so"
    volumes:
    - mount_path: "/usr/local/certificates"
      secret:
        from: config_store
        filter: secret=webhook-cert
    ports:
    - 80:80:443
    - 8443
    health:
      ready:
        type: http
        endpoint: "/healthz"
        port: 10254
        failure_threshold: 3
        initial_delay: 10
        period: 10
        success_threshold: 1
        timeout: 1
      alive:
        type: http
        endpoint: "/healthz"
        port: 10254
        failure_threshold: 5
        initial_delay: 10
        period: 10
        success_threshold: 1
        timeout: 1
    constraints:
      resources:
        requests:
          memory: 100m
          cpu: 90m
      servers:
        tags:
        - env=prod
