#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done

# Run jupyterlab
exec s6-setuidgid 1000:1000 jupyterlab --ip="0.0.0.0" --LabApp.token=""
