name: Build RStudio

on:
  push:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/build_and_publish_rstudio.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/build_and_publish_rstudio.yml'

jobs:
  build_and_publish_image:
    name: Build and Publish RStudio Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to GitHub Package Registry
        run: >
          echo $DOCKER_PASSWORD |
          docker login $DOCKER_REGISTRY_URL
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build and push the site builder image
        run: >
          cd rstudio &&
          make docker-build &&
          make docker-push

