name: Deploy Code

on: 
  workflow_dispatch: 
  pull_request:
  push:
    branches: 
    - main 
    - master
    paths:
    - "workspaces/code/**"
    - "modules/**"
    - ".github/workflows/code_deploy.yml"
    - ".github/workflows/terraform.yml"
    - ".github/workflows/docker.yml"

jobs:
  docker_image:
    name: Docker Image
    uses: ./.github/workflows/docker.yml
    with:
      image-path: workspaces/code/image
      image-name: code
  terraform_deployment:
    name: Terraform Deployment
    uses: ./.github/workflows/terraform.yml
    needs: docker_image
    with:
      workflow-path: workspaces/code
      terraform-version: 1.4.2
    secrets:
      terraform-api-token: ${{ secrets.TF_API_TOKEN }}
