name: Deploy RStudio to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/deploy_rstudio.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/deploy_rstudio.yml'

jobs:
  build_and_publish_rstudio_image:
    name: Build and Publish RStudio Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: >
          echo $DOCKER_PASSWORD |
          docker login
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Rstudio image
        run: >
          cd rstudio &&
          make docker-pull-latest &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  build_and_publish_gateway_image:
    name: Build and Publish Gateway Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: >
          echo $DOCKER_PASSWORD |
          docker login
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the gateway image
        run: >
          cd rstudio &&
          make docker-build-gateway &&
          make docker-push-gateway &&
          make docker-push-latest-gateway
  redeploy_rstudio:
    name: Redeploy RStudio
    needs: [build_and_publish_rstudio_image, build_and_publish_gateway_image]
    runs-on: ubuntu-latest
    steps:
      - name: Send Cloud66 redeployment webhook
        run: curl -X POST "$C66_REDEPLOY_URL?services=rstudio-gateway,rstudio,test-gateway"
        env:
          C66_REDEPLOY_URL: ${{ secrets.C66_REDEPLOY_URL }}
