name: Deploy VS Code to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'vscode/*'
    - '.github/workflows/deploy_vscode.yml'

jobs:
  build_and_publish_vscode_image:
    name: Build and Publish VS Code Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the VS Code image
        run: >
          cd vscode &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  # redeploy_vscode:
  #   name: Redeploy VS Code
  #   needs: [build_and_publish_vscode_image]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Cloud66 redeployment webhook
  #       run: curl -X POST "$C66_REDEPLOY_URL?services=vscode"
  #       env:
  #         C66_REDEPLOY_URL: ${{ secrets.VSCODE_C66_REDEPLOY_URL }}
