name: Deploy KeyCloak to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'keycloak/*'
    - '.github/workflows/deploy_keycloak.yml'

jobs:
  build_and_publish_keycloak_image:
    name: Build and Publish Keycloak Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: >
          echo $DOCKER_PASSWORD |
          docker login
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Keycloak image
        run: >
          cd rstudio &&
          make docker-pull-latest &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  redeploy_keycloak:
    name: Redeploy keycloak
    needs: [build_and_publish_keycloak_image]
    runs-on: ubuntu-latest
    steps:
      - name: Send Cloud66 redeployment webhook
        run: curl -X POST "$C66_REDEPLOY_URL?services=keycloak"
        env:
          C66_REDEPLOY_URL: ${{ secrets.C66_REDEPLOY_URL }}
