name: Deploy VS Code to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'vscode/*'
    - '.github/workflows/deploy_vscode.yml'

jobs:
  build_and_publish_vscode_image:
    name: Build and Publish VS Code Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: >
          echo $DOCKER_PASSWORD |
          docker login
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the VS Code image
        run: >
          cd vscode &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  redeploy_vscode:
    name: Redeploy VS Code
    needs: [build_and_publish_vscode_image]
    runs-on: ubuntu-latest
    steps:
      - name: Send Cloud66 redeployment webhook
        run: curl -X POST "$C66_REDEPLOY_URL?services=vscode"
        env:
          C66_REDEPLOY_URL: ${{ secrets.C66_REDEPLOY_URL }}
