name: Deploy KeyCloak to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'keycloak/**'
    - '.github/workflows/deploy_keycloak.yml'

jobs:
  build_and_publish_keycloak_image:
    name: Build and Publish Keycloak Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Keycloak image
        run: >
          cd keycloak &&
          make docker-pull-latest &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  redeploy_keycloak:
    name: Redeploy keycloak
    needs: [build_and_publish_keycloak_image]
    runs-on: ubuntu-latest
    steps:
      - name: Send Cloud66 redeployment webhook
        run: curl -X POST "$C66_REDEPLOY_URL?services=keycloak"
        env:
          C66_REDEPLOY_URL: ${{ secrets.KEYCLOAK_C66_REDEPLOY_URL }}
