name: Deploy Jupyter to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'jupyter/*'
    - '.github/workflows/deploy_jupyter.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'jupyter/*'
    - '.github/workflows/deploy_jupyter.yml'

jobs:
  build_and_publish_jupyter_image:
    name: Build and Publish Jupyter Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        run: >
          echo $DOCKER_PASSWORD |
          docker login
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Jupyter image
        run: >
          cd jupyter &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  redeploy_jupyter:
    name: Redeploy jupyter
    needs: [build_and_publish_jupyter_image]
    runs-on: ubuntu-latest
    steps:
      - name: Send Cloud66 redeployment webhook
        run: curl -X POST "$C66_REDEPLOY_URL?services=jupyter"
        env:
          C66_REDEPLOY_URL: ${{ secrets.C66_REDEPLOY_URL }}
