name: Deploy RStudio to TJCloud

on:
  push:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/build_and_publish_rstudio.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'rstudio/*'
    - '.github/workflows/build_and_publish_rstudio.yml'

jobs:
  build_and_publish_rstudio_image:
    name: Build and Publish RStudio Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to GitHub Package Registry
        run: >
          echo $DOCKER_PASSWORD |
          docker login $DOCKER_REGISTRY_URL
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build and push the Rstudio image
        run: >
          cd rstudio &&
          make docker-build &&
          make docker-push &&
          make docker-push-latest
  build_and_publish_gateway_image:
    name: Build and Publish Gateway Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Login to GitHub Package Registry
        run: >
          echo $DOCKER_PASSWORD |
          docker login $DOCKER_REGISTRY_URL
          --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build and push the gateway image
        run: >
          cd rstudio &&
          make docker-build-gateway &&
          make docker-push-gateway &&
          make docker-push-latest-gateway
  redeploy_rstudio:
    name: Redeploy RStudio
    needs: [build_and_publish_rstudio_image, build_and_publish_gateway_image]
    steps:
      - name: Send Cloud66 redeployment webhook
        run: >
          curl -X POST
          https://hooks.cloud66.com/stacks/redeploy/8bebb051db59a22cbd22d2f8bccdadd2/33be98d978dfa295d57849327b036814?services=rstudio-gateway,rstudio

