on:
  workflow_call:
    inputs:
      image-path:
        required: true
        type: string
      image-name:
        required: true 
        type: string
      image-tag:
        default: latest 
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.image-path }}
          push: true
          tags:  ${{ github.repository}}/${{ inputs.image-name }}:${{ inputs.image-tag }}
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
