name: Deploy Keycloak

on: 
  workflow_dispatch: 
  # pull_request:
  # push:
  #   branches: 
  #   - main 
  #   - master
  #   - dev/do_migration
  #   paths:
  #   - "workspaces/keycloak/**"
  #   - ".github/workflows/keycloak_deploy.yml"
  #   - ".github/workflows/terraform.yml"
  #   - ".github/workflows/docker.yml"

jobs:
  docker_image:
    name: Docker Image
    uses: ./.github/workflows/docker.yml
    with:
      image-path: workspaces/keycloak/image
      image-name: keycloak
